sonar.organization=pw9876
sonar.projectKey=pw9876_terraform-docker
sonar.projectName=terraform-docker
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/.github/**,**/tests/**,.dockerignore,.gitignore
